Pre requisite
DavidGeismarLtd/ZEDENTAL pull request #107
Opened 2020-11-30 19:49 UTC by DavidGeismarLtd

2020-11-30 20:40 UTC, ManyBaby requested changes
I think this is not why Pundit is made for.
Pundit is authorization based on who is the user and what ressources he/she is trying to access. 
You should have solved that issue with a default scope.

2020-12-01 19:33 UTC, DavidGeismarLtd commented
> I think this is not why Pundit is made for.
> Pundit is authorization based on who is the user and what ressources he/she is trying to access.
> You should have solved that issue with a default scope.

noted

2020-12-01 20:24 UTC, ManyBaby approved these changes

2020-12-01 20:24 UTC, ManyBaby commented on app/controllers/application_controller.rb
> +  include Pundit
We will use Pundit for other things

2020-12-01 20:26 UTC, ManyBaby approved these changes
On my phone I can't see if the published scope already existed on Program.
The rest seems good. Well played

2020-12-03 21:49 UTC, merged