Fix url for
DavidGeismarLtd/ZEDENTAL pull request #85
Opened 2020-11-13 19:13 UTC by DavidGeismarLtd

I m not sure why I was usng cloudinary url as it seems that with active storage url_for is the way to go : https://edgeguides.rubyonrails.org/active_storage_overview.html

What do you think @ManyBaby

2020-11-13 19:40 UTC, ManyBaby commented on app/helpers/editable_helper.rb
> +  # end
```suggestion

```

2020-11-13 19:42 UTC, ManyBaby commented on app/views/components/_big_card.html.erb
> +    <div class="bg-cover overflow-hidden rounded-lg mb-8" style="padding-top: 100%; background-image: url(<%= url_for_image program, :image_cover %>);"></div>
```suggestion
    <div class="bg-cover overflow-hidden rounded-lg mb-8" style="padding-top: 100%; background-image: url(<%= cl_image_path(program.image_cover.key) %>);"></div>
```

2020-11-13 19:43 UTC, ManyBaby commented on app/views/components/_carousel_card.html.erb
> +    style="background-image: linear-gradient(to bottom, rgba(221, 174, 208, 0.8), rgba(174, 172, 226, 0.8)), url('<%= url_for_image program, :image_cover %>'); filter: blur(3px);"
```suggestion
    style="background-image: linear-gradient(to bottom, rgba(221, 174, 208, 0.8), rgba(174, 172, 226, 0.8)), url('<%= cl_image_path(program.image_cover.key) %>'); filter: blur(3px);"
```

2020-11-13 19:44 UTC, ManyBaby requested changes
I think the correct way to do it is by using the cl_image_path helper supplied by the cloudinary gem. No need to reinvent the wheel here https://cloudinary.com/documentation/rails_image_manipulation#direct_url_building

2020-11-14 08:54 UTC, ManyBaby approved these changes
I made some suggestions but I think cl_image_path is the way to go when you want the url of an image hosted on Cloudinary via ActiveStorage.

2020-11-14 08:54 UTC, ManyBaby commented on app/helpers/editable_helper.rb
>    end
```suggestion

```

2020-11-14 08:54 UTC, ManyBaby commented on app/helpers/editable_helper.rb
>    end
I think that you should remove the `url_for_image` method definition as it is not useful. And rename the `cloudinary_path` method to `url_for_image` as this naming is more agnostic to the hosting service we use.

2020-11-14 08:54 UTC, ManyBaby commented on app/helpers/editable_helper.rb
> +  # end
```suggestion
  # define a constant in the class for the fallback image url, it could even be a env var for more flexibility
  FALLBACK_IMAGE = "https://res.cloudinary.com/dockcyr0z/image/upload/v1598369435/vb13pcfoit64mylb2zzob0pzbt1n.jpg"

   def url_for_image(field, image_method = :image)
     return cl_image_path(field.send(image_method).key) if field.send(image_method).attached?
     FALLBACK_IMAGE
   end
```

2020-11-14 09:27 UTC, DavidGeismarLtd commented
> I think the correct way to do it is by using the cl_image_path helper supplied by the cloudinary gem. No need to reinvent the wheel here https://cloudinary.com/documentation/rails_image_manipulation#direct_url_building

I dont agree with you. It is not about reinventing the wheel. This is what the rails documentation says about url_for

`"Generate a permanent URL for the blob that points to the application. Upon access, a redirect to the actual service endpoint is returned. This indirection decouples the service URL from the actual one, and allows, for example, mirroring attachments in different services for high-availability. The redirection has an HTTP expiration of 5 min."`

the important part is  `a redirect to the actual service endpoint is returned. This indirection decouples the service URL from the actual one`. `url_for` was made to decouple active_storage from any service provider, so you can actually plug any storage provider and not have to change your code. @ManyBaby

2020-11-15 19:49 UTC, merged